language:
  - php
  - c

compiler:
  - gcc
  - clang

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - sudo apt-get -qq install libmcrypt-dev libssl-dev valgrind

before_script:
  - phpize && ./configure CFLAGS="-O1 -g3 -Wall -Werror" && make --silent
  - ulimit -c unlimited

script:
  - ./.travis/run_php_tests.sh

after_failure:
  - ./.travis/after_failure.sh

